---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 洪金敏.
--- DateTime: 2021/8/1 13:25
---

local binder = require("Binder")
local Panel = {}

function Panel:Load()
    self.gameObject = ModuleManager.GetInstance():OpenSample()
    self.btn_go = self.gameObject.transform:Find("Button")
    self.result_text = self.gameObject.transform:Find("ResultText"):GetComponent("XTextField")
end

function Panel:Start()
    binder.bind_component(self.role_data, "age", self.result_text, slot(self.TextBinderFunc, self))
    binder.bind_component(self.role_data, "name", self.result_text, slot(self.TextBinderFunc, self))
    self.btn_go:GetComponent("XButton").onClick:AddListener(function(obj)
        -- 改变数据
        self.role_data.age = self.role_data.age + 1
        self.role_data.name = "role_" .. tostring(self.role_data.age)
    end)
end

function Panel:TextBinderFunc(data, component)
    component.text = tostring(data.name) .. "   " .. tostring(data.age)
end

function Panel:Refresh(role_data)
    -- 数据绑定
    self.role_data = role_data
end

return Panel