//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ModuleManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ModuleManager), typeof(System.Object));
		L.RegFunction("OpenSample", OpenSample);
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("New", _CreateModuleManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateModuleManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ModuleManager obj = new ModuleManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ModuleManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenSample(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ModuleManager obj = (ModuleManager)ToLua.CheckObject<ModuleManager>(L, 1);
			UnityEngine.GameObject o = obj.OpenSample();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			ModuleManager o = ModuleManager.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

